// Auto-generated by generate_aot_kernels. Do not edit.
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 7.246200084686279
constexpr double laplace_2d_2[] = {
     3.29321903466126165e-01, -4.32915591245016218e-01, 1.36743201866307562e-01, -4.30970698263257665e-02,
     1.03361830425524083e-02
};

// beta: 7.246200084686279
constexpr double laplace_2d_3[] = {
     3.29321903466126165e-01, -4.32915591245016218e-01, 1.36743201866307562e-01, -4.30970698263257665e-02,
     1.03361830425524083e-02
};

// beta: 13.739999771118164
constexpr double laplace_2d_4[] = {
     3.44985101657607596e-01, -4.90563999366436465e-01, 2.22154658821504564e-01, -1.13210290038759251e-01,
     5.48205844183722521e-02, -2.70581725776911156e-02, 8.90321565147650547e-03
};

// beta: 13.739999771118164
constexpr double laplace_2d_5[] = {
     3.44980453081457139e-01, -4.90291157596230098e-01, 2.22238751814785113e-01, -1.15402517179068742e-01,
     5.45957746481164977e-02, -2.26622742958871790e-02, 9.05331403273746706e-03, -2.51631150680736932e-03
};

// beta: 13.739999771118164
constexpr double laplace_2d_6[] = {
     3.44985101657607596e-01, -4.90287828480653998e-01, 2.22089411666970604e-01, -1.15429215524819676e-01,
     5.53442415664025592e-02, -2.26087988730898082e-02, 7.85387818920790098e-03, -2.54689892724176224e-03,
     6.00393525042385067e-04
};

// beta: 20.736000061035156
constexpr double laplace_2d_7[] = {
     3.46428527775225148e-01, -4.98750712419561593e-01, 2.44865366070722068e-01, -1.53122183334882644e-01,
     9.89505536231822386e-02, -6.06406481318446586e-02, 3.38160353960700322e-02, -1.66107775675107608e-02,
     6.90910688630542742e-03, -2.65713478968165667e-03, 1.12653747400457641e-03, -3.14701937237024231e-04
};

// beta: 20.736000061035156
constexpr double laplace_2d_8[] = {
     3.46428566144110717e-01, -4.98750664703613233e-01, 2.44862593938898088e-01, -1.53123140038410793e-01,
     9.89829753193193357e-02, -6.06352810208430210e-02, 3.36774454808130702e-02, -1.66230616955124651e-02,
     7.17677435651219078e-03, -2.64483784948591014e-03, 8.88335209187525020e-04, -3.19177283643670750e-04,
     7.94760276904927848e-05
};

// beta: 20.736000061035156
constexpr double laplace_2d_9[] = {
     3.46428566581879593e-01, -4.98750721080790493e-01, 2.44862562347629098e-01, -1.53121557982202422e-01,
     9.89833444854674588e-02, -6.06479585066602642e-02, 3.36758684431487446e-02, -1.65795398095903851e-02,
     7.17981868415975329e-03, -2.71744941052586703e-03, 8.85627076974427750e-04, -2.61038825301749308e-04,
     8.03793016406761251e-05, -1.79013872301325826e-05
};

// beta: 27.8700008392334
constexpr double laplace_2d_10[] = {
     3.46559742211937971e-01, -4.99845494910857613e-01, 2.49169718480321989e-01, -1.63791349756075538e-01,
     1.17747452496520799e-01, -8.57018614709624399e-02, 6.02075737045049061e-02, -3.95571932756455663e-02,
     2.38257729575048864e-02, -1.30010692824873274e-02, 6.40740211036577422e-03, -2.86437470583869114e-03,
     1.14054228634538624e-03, -3.86826107828082833e-04, 1.28590502212932902e-04, -5.20354408545300657e-05,
     1.34102406720241787e-05
};

// beta: 27.8700008392334
constexpr double laplace_2d_11[] = {
     3.46559742217290301e-01, -4.99845495736832346e-01, 2.49169717793705420e-01, -1.63791310022705944e-01,
     1.17747466940543319e-01, -8.57024187111174868e-02, 6.02074579917375105e-02, -3.95536856071848214e-02,
     2.38262280603695337e-02, -1.30127754719019540e-02, 6.40643030366388339e-03, -2.84221699072803417e-03,
     1.14169170707088320e-03, -4.10708945624273247e-04, 1.27882679527168509e-04, -3.83778495917228626e-05,
     1.35873019331030945e-05, -3.21566448226323168e-06
};

// beta: 27.8700008392334
constexpr double laplace_2d_12[] = {
     3.46559742211937971e-01, -4.99845495746086943e-01, 2.49169718662481776e-01, -1.63791309577828254e-01,
     1.17747443736300403e-01, -8.57024249470426935e-02, 6.02076965329289351e-02, -3.95536463701684840e-02,
     2.38249999416504966e-02, -1.30129063726664718e-02, 6.40998147047111295e-03, -2.84196929227711675e-03,
     1.13566072697733871e-03, -4.10975860904817867e-04, 1.33851465500321845e-04, -3.82252460026319418e-05,
     1.04020443628198410e-05, -3.25158774335931056e-06, 7.08208684211445262e-07
};


template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_laplace_2d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 2) {
        constexpr int ND = 2, NC = 5;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_2, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 5;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 7;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 8;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 9;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 12;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 13;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 14;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 17;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 18;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 19;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}
// beta: 7.246200084686279
constexpr double laplace_3d_2[] = {
     1.62776157909298641e-01, -4.63792019471840733e-01, 4.14170492893857989e-01, -3.76863808733320232e-02,
     -7.75366712988954654e-02
};

// beta: 7.246200084686279
constexpr double laplace_3d_3[] = {
     1.63089591153904173e-01, -4.54950773775829098e-01, 4.11700837330796821e-01, -7.23719521065141341e-02,
     -7.50794043594266991e-02, 2.74805671992044108e-02
};

// beta: 13.739999771118164
constexpr double laplace_3d_4[] = {
     5.48252760469883985e-02, -2.61783535701059500e-01, 4.86487421730133096e-01, -3.87776203409937958e-01,
     1.33856880233848025e-02, 1.81137381262840541e-01, -7.59864381050642523e-02, -3.15920801564063616e-02,
     2.13087440219718108e-02
};

// beta: 13.739999771118164
constexpr double laplace_3d_5[] = {
     5.48252760469883499e-02, -2.61657003845425618e-01, 4.86275812116020500e-01, -3.89471337321823430e-01,
     1.61663962425033329e-02, 1.87256907658528482e-01, -8.59012692555918417e-02, -3.97664495268407400e-02,
     3.44385253140234299e-02, 3.63778591948655172e-03, -5.80571681770739381e-03
};

// beta: 13.739999771118164
constexpr double laplace_3d_6[] = {
     5.48247347249668712e-02, -2.61659644769781707e-01, 4.86302537734574880e-01, -3.89421091530544050e-01,
     1.59543689259425518e-02, 1.86985514844604905e-01, -8.53111033497927912e-02, -3.91628971379871099e-02,
     3.37670338742791787e-02, 3.04709406149256817e-03, -5.53804300866320154e-03, 2.11095883923119579e-04
};

// beta: 20.736000061035156
constexpr double laplace_3d_7[] = {
     1.83571872702758994e-02, -1.25800646698177893e-01, 3.60948227810086508e-01, -5.31493092995817373e-01,
     3.44774655560168342e-01, 9.70294280536392328e-02, -3.12632363727397000e-01, 1.30397833662786705e-01,
     9.87287081067854122e-02, -9.75666128978080055e-02, -6.34817584426848082e-03, 3.22610020185652088e-02,
     -5.18993690847613636e-03, -4.82796576412116134e-03, 1.36172435564773059e-03
};

// beta: 20.736000061035156
constexpr double laplace_3d_8[] = {
     1.83571872702758716e-02, -1.25801550246796123e-01, 3.60948700131149991e-01, -5.31459608970370478e-01,
     3.44757250781569824e-01, 9.66698708638936699e-02, -3.12446273084851178e-01, 1.32102172367788401e-01,
     9.78496197487078168e-02, -1.01717173250503806e-01, -4.21324325954494823e-03, 3.76775101751810407e-02,
     -7.96968161052202979e-03, -8.42943897016764157e-03, 3.20644791622921648e-03, 9.58219943867784450e-04,
     -4.90009498943341630e-04
};

// beta: 20.736000061035156
constexpr double laplace_3d_9[] = {
     1.83571881884711172e-02, -1.25801585248739051e-01, 3.60948583864217520e-01, -5.31457934670654608e-01,
     3.44759672147210039e-01, 9.66464960609163815e-02, -3.12465516228357165e-01, 1.32248761531588738e-01,
     9.79248113977406187e-02, -1.02204860553113869e-01, -4.37293565060375544e-03, 3.85981685048875992e-02,
     -7.78166579449560657e-03, -9.41951604192033110e-03, 3.09111906251203963e-03, 1.52328293324353707e-03,
     -4.61257753096640678e-04, -1.32812592234632972e-04
};

// beta: 27.8700008392334
constexpr double laplace_3d_10[] = {
     6.26247256151976107e-03, -5.60574293702892426e-02, 2.18589090067185743e-01, -4.71735027326395884e-01,
     5.66967877131087761e-01, -2.51160821642421650e-01, -2.74450089449097823e-01, 4.58254888117719861e-01,
     -1.39791021729694986e-01, -2.13193398822660779e-01, 1.99637746358729190e-01, 1.80145003084325565e-02,
     -1.03773572010651446e-01, 3.01209504111669413e-02, 3.20669967554832250e-02, -1.98918568101065195e-02,
     -6.09021945044493657e-03, 7.01526317186287537e-03, 5.87728792191125667e-04, -1.53449644682176426e-03,
     -7.00901601450849506e-06, 1.67428423374787740e-04
};

// beta: 27.8700008392334
constexpr double laplace_3d_11[] = {
     6.26247257642206095e-03, -5.60574295322629340e-02, 2.18589086517959330e-01, -4.71735015521678125e-01,
     5.66968017234164012e-01, -2.51161075317248905e-01, -2.74452250848556067e-01, 4.58257389848074459e-01,
     -1.39773894148497502e-01, -2.13206969043788525e-01, 1.99558471306609003e-01, 1.80587700887507030e-02,
     -1.03544600133344225e-01, 3.00303939314476645e-02, 3.16419364246514484e-02, -1.97748528705253140e-02,
     -5.58299291709410048e-03, 6.92255099151397029e-03, 2.11679264322582367e-04, -1.49337137703211610e-03,
     1.50618141482949150e-04, 1.59608809420174868e-04, -2.85434202876419262e-05
};

// beta: 27.8700008392334
constexpr double laplace_3d_12[] = {
     6.26247257642206095e-03, -5.60574293612936536e-02, 2.18589086458903487e-01, -4.71735030480264772e-01,
     5.66968022387051906e-01, -2.51160688282184741e-01, -2.74452383824227431e-01, 4.58252764690880332e-01,
     -1.39772308749797597e-01, -2.13176245214767662e-01, 1.99547961370486304e-01, 1.79340320431477032e-02,
     -1.03502006664385554e-01, 3.03557323058626198e-02, 3.15310216647186059e-02, -2.03312107921569396e-02,
     -5.39358634342475100e-03, 7.54300285024031569e-03, 7.18969073072858556e-07, -1.92792010947438275e-03,
     2.98201895265043631e-04, 3.33119392955277794e-04, -8.74116730715449443e-05, -3.01270431963363916e-05,
     1.02119331167082956e-05
};


template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_laplace_3d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 2) {
        constexpr int ND = 2, NC = 5;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_2, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 6;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 9;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 11;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 12;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 15;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 17;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 18;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 22;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 23;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 25;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}
// beta: 7.246200084686279
constexpr double sqrt_laplace_2d_2[] = {
     1.62776157909298641e-01, -4.63792019471840733e-01, 4.14170492893857989e-01, -3.76863808733320232e-02,
     -7.75366712988954654e-02
};

// beta: 7.246200084686279
constexpr double sqrt_laplace_2d_3[] = {
     1.63089591153904173e-01, -4.54950773775829098e-01, 4.11700837330796821e-01, -7.23719521065141341e-02,
     -7.50794043594266991e-02, 2.74805671992044108e-02
};

// beta: 13.739999771118164
constexpr double sqrt_laplace_2d_4[] = {
     5.48252760469883985e-02, -2.61783535701059500e-01, 4.86487421730133096e-01, -3.87776203409937958e-01,
     1.33856880233848025e-02, 1.81137381262840541e-01, -7.59864381050642523e-02, -3.15920801564063616e-02,
     2.13087440219718108e-02
};

// beta: 13.739999771118164
constexpr double sqrt_laplace_2d_5[] = {
     5.48252760469883499e-02, -2.61657003845425618e-01, 4.86275812116020500e-01, -3.89471337321823430e-01,
     1.61663962425033329e-02, 1.87256907658528482e-01, -8.59012692555918417e-02, -3.97664495268407400e-02,
     3.44385253140234299e-02, 3.63778591948655172e-03, -5.80571681770739381e-03
};

// beta: 13.739999771118164
constexpr double sqrt_laplace_2d_6[] = {
     5.48247347249668712e-02, -2.61659644769781707e-01, 4.86302537734574880e-01, -3.89421091530544050e-01,
     1.59543689259425518e-02, 1.86985514844604905e-01, -8.53111033497927912e-02, -3.91628971379871099e-02,
     3.37670338742791787e-02, 3.04709406149256817e-03, -5.53804300866320154e-03, 2.11095883923119579e-04
};

// beta: 20.736000061035156
constexpr double sqrt_laplace_2d_7[] = {
     1.83571872702758994e-02, -1.25800646698177893e-01, 3.60948227810086508e-01, -5.31493092995817373e-01,
     3.44774655560168342e-01, 9.70294280536392328e-02, -3.12632363727397000e-01, 1.30397833662786705e-01,
     9.87287081067854122e-02, -9.75666128978080055e-02, -6.34817584426848082e-03, 3.22610020185652088e-02,
     -5.18993690847613636e-03, -4.82796576412116134e-03, 1.36172435564773059e-03
};

// beta: 20.736000061035156
constexpr double sqrt_laplace_2d_8[] = {
     1.83571872702758716e-02, -1.25801550246796123e-01, 3.60948700131149991e-01, -5.31459608970370478e-01,
     3.44757250781569824e-01, 9.66698708638936699e-02, -3.12446273084851178e-01, 1.32102172367788401e-01,
     9.78496197487078168e-02, -1.01717173250503806e-01, -4.21324325954494823e-03, 3.76775101751810407e-02,
     -7.96968161052202979e-03, -8.42943897016764157e-03, 3.20644791622921648e-03, 9.58219943867784450e-04,
     -4.90009498943341630e-04
};

// beta: 20.736000061035156
constexpr double sqrt_laplace_2d_9[] = {
     1.83571881884711172e-02, -1.25801585248739051e-01, 3.60948583864217520e-01, -5.31457934670654608e-01,
     3.44759672147210039e-01, 9.66464960609163815e-02, -3.12465516228357165e-01, 1.32248761531588738e-01,
     9.79248113977406187e-02, -1.02204860553113869e-01, -4.37293565060375544e-03, 3.85981685048875992e-02,
     -7.78166579449560657e-03, -9.41951604192033110e-03, 3.09111906251203963e-03, 1.52328293324353707e-03,
     -4.61257753096640678e-04, -1.32812592234632972e-04
};

// beta: 27.8700008392334
constexpr double sqrt_laplace_2d_10[] = {
     6.26247256151976107e-03, -5.60574293702892426e-02, 2.18589090067185743e-01, -4.71735027326395884e-01,
     5.66967877131087761e-01, -2.51160821642421650e-01, -2.74450089449097823e-01, 4.58254888117719861e-01,
     -1.39791021729694986e-01, -2.13193398822660779e-01, 1.99637746358729190e-01, 1.80145003084325565e-02,
     -1.03773572010651446e-01, 3.01209504111669413e-02, 3.20669967554832250e-02, -1.98918568101065195e-02,
     -6.09021945044493657e-03, 7.01526317186287537e-03, 5.87728792191125667e-04, -1.53449644682176426e-03,
     -7.00901601450849506e-06, 1.67428423374787740e-04
};

// beta: 27.8700008392334
constexpr double sqrt_laplace_2d_11[] = {
     6.26247257642206095e-03, -5.60574295322629340e-02, 2.18589086517959330e-01, -4.71735015521678125e-01,
     5.66968017234164012e-01, -2.51161075317248905e-01, -2.74452250848556067e-01, 4.58257389848074459e-01,
     -1.39773894148497502e-01, -2.13206969043788525e-01, 1.99558471306609003e-01, 1.80587700887507030e-02,
     -1.03544600133344225e-01, 3.00303939314476645e-02, 3.16419364246514484e-02, -1.97748528705253140e-02,
     -5.58299291709410048e-03, 6.92255099151397029e-03, 2.11679264322582367e-04, -1.49337137703211610e-03,
     1.50618141482949150e-04, 1.59608809420174868e-04, -2.85434202876419262e-05
};

// beta: 27.8700008392334
constexpr double sqrt_laplace_2d_12[] = {
     6.26247257642206095e-03, -5.60574293612936536e-02, 2.18589086458903487e-01, -4.71735030480264772e-01,
     5.66968022387051906e-01, -2.51160688282184741e-01, -2.74452383824227431e-01, 4.58252764690880332e-01,
     -1.39772308749797597e-01, -2.13176245214767662e-01, 1.99547961370486304e-01, 1.79340320431477032e-02,
     -1.03502006664385554e-01, 3.03557323058626198e-02, 3.15310216647186059e-02, -2.03312107921569396e-02,
     -5.39358634342475100e-03, 7.54300285024031569e-03, 7.18969073072858556e-07, -1.92792010947438275e-03,
     2.98201895265043631e-04, 3.33119392955277794e-04, -8.74116730715449443e-05, -3.01270431963363916e-05,
     1.02119331167082956e-05
};


template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_sqrt_laplace_2d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 2) {
        constexpr int ND = 2, NC = 5;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_2, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 6;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 9;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 11;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 12;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 15;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 17;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 18;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 22;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 23;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 25;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}
// beta: 7.246200084686279
constexpr double sqrt_laplace_3d_2[] = {
     1.07161047080465935e-01, -2.88571474311499654e-01, 3.20321770335918854e-01, -2.10324536751387570e-01,
     7.23279846938904708e-02
};

// beta: 7.246200084686279
constexpr double sqrt_laplace_3d_3[] = {
     1.07254718994902187e-01, -2.93981085471008985e-01, 3.19570545856513233e-01, -1.88637237549283271e-01,
     7.30798266492501541e-02, -1.73694010974015031e-02
};

// beta: 13.739999771118164
constexpr double sqrt_laplace_3d_4[] = {
     1.60736327537340622e-02, -8.10259690509166908e-02, 1.84467015108034149e-01, -2.45158447791891249e-01,
     2.09783847695839382e-01, -1.41815912988725867e-01, 8.95982544786763924e-02, -3.19810585034823944e-02
};

// beta: 13.739999771118164
constexpr double sqrt_laplace_3d_5[] = {
     1.61480322511267926e-02, -8.10440877195417186e-02, 1.82073133444159208e-01, -2.44576376070280099e-01,
     2.21792792965626040e-01, -1.44733126003470491e-01, 7.03416386099365021e-02, -2.73061894796408806e-02,
     9.64344436079391139e-03, -2.34005533844518264e-03
};

// beta: 13.739999771118164
constexpr double sqrt_laplace_3d_6[] = {
     1.61470984321902232e-02, -8.10448220669755248e-02, 1.82119933749507773e-01, -2.44566570073086464e-01,
     2.21417805621718394e-01, -1.44768462930523117e-01, 7.13927749673291118e-02, -2.72590398871177773e-02,
     8.44114013142997950e-03, -2.36102195069053632e-03, 4.81234778450322304e-04
};

// beta: 20.736000061035156
constexpr double sqrt_laplace_3d_7[] = {
     2.08641524535035667e-03, -1.56208947542262281e-02, 5.44491303138174010e-02, -1.17853851924112504e-01,
     1.78333541989026401e-01, -2.01374285316365337e-01, 1.76926335869502627e-01, -1.24830062655316321e-01,
     7.25686122220910584e-02, -3.49460129946371767e-02, 1.37592549991494232e-02, -4.89877085829435420e-03,
     1.87669573475343090e-03, -4.76118763041106087e-04
};

// beta: 20.736000061035156
constexpr double sqrt_laplace_3d_8[] = {
     2.08640211236377649e-03, -1.56209121521473284e-02, 5.44504204980769888e-02, -1.17853363905131236e-01,
     1.78312861092666197e-01, -2.01378194744893824e-01, 1.77050598773452528e-01, -1.24816644803869364e-01,
     7.22131688347936451e-02, -3.49683949009441039e-02, 1.42810604867677181e-02, -4.88085300150229752e-03,
     1.49690442387500591e-03, -4.81635114364917065e-04, 1.08583529847119413e-04
};

// beta: 20.736000061035156
constexpr double sqrt_laplace_3d_9[] = {
     2.08640199052400515e-03, -1.56208920807006397e-02, 5.44504324575594625e-02, -1.17854114448096736e-01,
     1.78312669510175686e-01, -2.01370078701715222e-01, 1.77051749347173770e-01, -1.24855331473128398e-01,
     7.22098790120973555e-02, -3.48737496949526049e-02, 1.42858885264931686e-02, -5.00483713389696452e-03,
     1.49339132271768824e-03, -3.98931062472084952e-04, 1.09587708430315068e-04, -2.20653847480378520e-05
};

// beta: 27.8700008392334
constexpr double sqrt_laplace_3d_10[] = {
     2.58525692186872987e-04, -2.58698778280192117e-03, 1.22822964600856066e-02, -3.68930702803809546e-02,
     7.88964627586280359e-02, -1.28181528858425597e-01, 1.64896250224564306e-01, -1.72875572764064844e-01,
     1.50907061408529775e-01, -1.11530218653708602e-01, 7.07015225258522950e-02, -3.88425175551009166e-02,
     1.87150428995368143e-02, -8.01665565586290665e-03, 3.01846967871270428e-03, -9.63142504699299228e-04,
     2.98000418957530594e-04, -1.10305922000410015e-04, 2.63679283275102479e-05
};

// beta: 27.8700008392334
constexpr double sqrt_laplace_3d_11[] = {
     2.58525689933281522e-04, -2.58698736253545978e-03, 1.22822968258063953e-02, -3.68930955391947937e-02,
     7.88964529930965691e-02, -1.28181083685009495e-01, 1.64896350592791147e-01, -1.72879138285080058e-01,
     1.50906544760054079e-01, -1.11514752872688097e-01, 7.07030162193709039e-02, -3.88819181965701435e-02,
     1.87125064608807887e-02, -7.95599495735509372e-03, 3.02097969513667177e-03, -1.01863921743943907e-03,
     2.96661064465573109e-04, -8.25418873582902757e-05, 2.66656961362198151e-05, -5.84799633765873277e-06
};

// beta: 27.8700008392334
constexpr double sqrt_laplace_3d_12[] = {
     2.58525692186872987e-04, -2.58698735851683927e-03, 1.22822963744048334e-02, -3.68930957809190871e-02,
     7.88964679081206599e-02, -1.28181079424181804e-01, 1.64896159482776555e-01, -1.72879172408193782e-01,
     1.50907788065909293e-01, -1.11514604884069099e-01, 7.06983710372832280e-02, -3.88822951459712254e-02,
     1.87230706280595779e-02, -7.95541471190883663e-03, 3.00611164453150337e-03, -1.01916998062426007e-03,
     3.09305345793736263e-04, -8.22763956418475135e-05, 2.07127473967709248e-05, -5.90390975561397717e-06,
     1.19107349970371013e-06
};


template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_sqrt_laplace_3d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 2) {
        constexpr int ND = 2, NC = 5;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_2, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 6;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 8;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 10;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 11;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 14;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 15;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 16;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 19;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 20;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 21;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,
                                    int n_src, const Real *r_src, const Real *charge,
                                    int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(
                eval_level, ND, rsc, cen, d2max, thresh2, NC,
                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}

// Explicit instantiations
template direct_evaluator_func<float>
get_laplace_2d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double>
get_laplace_2d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);
template direct_evaluator_func<float>
get_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double>
get_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);
template direct_evaluator_func<float>
get_sqrt_laplace_2d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double>
get_sqrt_laplace_2d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);
template direct_evaluator_func<float>
get_sqrt_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double>
get_sqrt_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);

} // namespace dmk
